
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygsqgosylxoiqikxlsil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnc3Fnb3N5bHhvaXFpa3hsc2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTM3MzAsImV4cCI6MjA1NzcyOTczMH0.lvW9irUAsx7muYbZFMONIf8dhUyW8mBxLG2mUe_K03Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    // Increase timeout to handle potentially slow connections
    fetch: (url, options) => {
      return fetch(url, {
        ...options,
        signal: options?.signal || AbortSignal.timeout(60000), // 60 seconds (1 minute) timeout
      });
    },
  },
});
